In [9]:
# emtpy lattice
lattice = []

# creating a range
x_range = range(-3, 3)
y_range = range(-3, 3)

# using nested for loops
for x in x_range:
    for y in y_range:
        lattice.append((x, y))

# printing the lattice combine python
print(lattice)

[(-3, -3), (-3, -2), (-3, -1), (-3, 0), (-3, 1), (-3, 2), (-2, -3), (-2, -2), (-2, -1), (-2, 0), (-2, 1), (-2, 2), (-1, -3), (-1, -2), (-1, -1), (-1, 0), (-1, 1), (-1, 2), (0, -3), (0, -2), (0, -1), (0, 0), (0, 1), (0, 2), (1, -3), (1, -2), (1, -1), (1, 0), (1, 1), (1, 2), (2, -3), (2, -2), (2, -1), (2, 0), (2, 1), (2, 2)]


In [13]:
# importing the module
import numpy as np

# creating lline space
x = np.linspace(-3, 3, 3)
y = np.linspace(-3, 3, 3)

# using meshgrid function
X, Y = np.meshgrid(x, y)
lattice = np.dstack((X, Y))

print(lattice)

[[[-3. -3.]
  [ 0. -3.]
  [ 3. -3.]]

 [[-3.  0.]
  [ 0.  0.]
  [ 3.  0.]]

 [[-3.  3.]
  [ 0.  3.]
  [ 3.  3.]]]


In [14]:
# importing itertools
from itertools import product

# generating the values
x_values = [-3, -2, 0, 2, 3]
y_values = [-3, -2, 0, 2, 3]

# generating lattice combine in Python
lattice = list(product(x_values, y_values))

# printing
print(lattice)

[(-3, -3), (-3, -2), (-3, 0), (-3, 2), (-3, 3), (-2, -3), (-2, -2), (-2, 0), (-2, 2), (-2, 3), (0, -3), (0, -2), (0, 0), (0, 2), (0, 3), (2, -3), (2, -2), (2, 0), (2, 2), (2, 3), (3, -3), (3, -2), (3, 0), (3, 2), (3, 3)]


In [17]:
import tenpy

ImportError: cssselect does not seem to be installed. See http://packages.python.org/cssselect/