In [36]:
# %pip install tensorflow

In [37]:
import tensorflow as tf

In [38]:
# #printing the version of installed module
print(ts.__version__)

2.9.1


In [39]:
# defining varriables
a = 4
b = 5

# addition using tensorflow
Sum = tf.add(a, b, name='Add')

# printing the sum
print(Sum)

Tensor("Add_2:0", shape=(), dtype=int32)


In [40]:
# tf.executing_eagerly()

In [41]:
# creating session
with tf.compat.v1.Session() as sess:

    # printing the sum with session
    print(sess.run(Sum))
 

9


In [45]:
x = 2
y = 3
add_op = tf.add(x, y, name='Add')
mul_op = tf.multiply(x, y, name='Multiply')
pow_op = tf.pow(add_op, mul_op, name='Power')
useless_op = tf.multiply(x, add_op, name='Useless')

with tf.compat.v1.Session() as sess:
    pow_out, useless_out = sess.run([pow_op, useless_op])
    print(pow_out)
    print(useless_out)

15625
10


In [46]:
# create constants
a = tf.constant(5)
b = tf.constant(4)

# Adding constants
Sun = a + b

# launch the graph in a session
with tf.compat.v1.Session() as sess:
    print(sess.run(Sum))

9


In [48]:
# Creating floating number
floating = tf.constant(5.3, name='scalar', dtype=tf.float32)

# creating matrix 
matrix = tf.constant([[1, 2], [3, 4]], name='matrix')

# launch the graph in a session
with tf.compat.v1.Session() as sess:
    print(sess.run(floating))
    print('\n')
    print(sess.run(matrix))

5.3


[[1 2]
 [3 4]]


In [50]:
a = tf.get_variable(name="var1", initializer=tf.constant(2))
b = tf.get_variable(name="var2", initializer=tf.constant(3.543))

# launch the graph in a session
with tf.Session() as sess:
    # now let's evaluate their value
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))

AttributeError: module 'tensorflow' has no attribute 'get_variable'

In [57]:
# create variables and initializing values
integer_value = tf.compat.v1.get_variable(name="var1", initializer=tf.constant(2))
floating_value = tf.compat.v1.get_variable(name="var2", initializer=tf.constant(3.54))

# add an Op to initialize global variables
init_op = tf.compat.v1.global_variables_initializer()

# launch the graph in a session
with tf.compat.v1.Session() as sess:
    
    # run the variable initializer operation
    sess.run(init_op)
    
    # printing valus of varibles
    print(sess.run(integer_value))
    print(sess.run(floating_value))


2
3.54


In [62]:
# defining constand
cont = tf.constant([0, 0, 0], tf.float32, name='A')

# defining a place holder ( empty)
placeHolder = tf.compat.v1.placeholder(tf.float32, shape=[3], name='B')

# Adding constant and placeholder
Sum = tf.add(cont, placeHolder, name="Add")

with tf.compat.v1.Session() as sess:
    
    # create a dictionary assigning to placeholder
    d = {placeHolder: [1, 2, 3]}
    
    
    # feed it to the placeholder
    print(sess.run(Sum, feed_dict=d)) 

[1. 2. 3.]


In [76]:
# To clear the defined variables and operations of the previous cell
tf.compat.v1.reset_default_graph()   

# create graph
a = tf.constant(10,name="a")
b = tf.constant(3, name="b")
c = tf.add(a, b, name="addition")
d = tf.math.multiply(c, a, name='multiplication')
f = tf.add(c, d, name='Final')

# launch the graph in a session
with tf.compat.v1.Session() as sess:
    # or creating the writer inside the session
    writer = tf.compat.v1.summary.FileWriter('./graphs', sess.graph)

In [86]:
# To clear the defined variables and operations of the previous cell
tf.compat.v1.reset_default_graph()   

# create the scalar variable from normal distribution
x_scalar = tf.compat.v1.get_variable('x_scalar', shape=[], initializer=tf.compat.v1.truncated_normal_initializer(mean=0, stddev=1))

# create the scalar summary
first_summary = tf.compat.v1.summary.scalar(name='Summary_of_random_variables', tensor=x_scalar)

# initializing the global variable
init = tf.compat.v1.global_variables_initializer()

# launch the graph in a session
with tf.compat.v1.Session() as sess:
    
    # creating the writer inside the session
    writer = tf.compat.v1.summary.FileWriter('./graphs', sess.graph)
    for step in range(100):
        
        # loop over several initializations of the variable
        sess.run(init)
        
        # evaluate the scalar summary
        summary = sess.run(first_summary)
        
        #add the summary to the writer
        writer.add_summary(summary, step)

In [90]:
 # To clear the defined variables and operations of the previous cell
tf.compat.v1.reset_default_graph()  

# create the variables
x_matrix = tf.compat.v1.get_variable('x_matrix', shape=[40, 40], initializer=tf.compat.v1.truncated_normal_initializer(mean=0, stddev=1))

# A histogram summary for the non-scalar tensor
histogram_summary = tf.compat.v1.summary.histogram('histogram_summary', x_matrix)

init = tf.compat.v1.global_variables_initializer()

# launch the graph in a session
with tf.compat.v1.Session() as sess:
    
    # creating the writer inside the session
    writer = tf.compat.v1.summary.FileWriter('./graphs', sess.graph)
    for step in range(100):
        # loop over several initializations of the variable
        sess.run(init)
        # evaluate the merged summaries
        summary = sess.run(histogram_summary)
        
        # the histogram summary
        writer.add_summary(summary, step)

In [ ]:
 # To clear the defined variables and operations of the previous cell
tf.reset_default_graph()  

# create the variables for colored and grayscale images
w_gray = tf.get_variable('W_Grayscale', shape=[50, 30], initializer=tf.truncated_normal_initializer(mean=0, stddev=1))
w_color = tf.get_variable('W_Color', shape=[50, 30], initializer=tf.truncated_normal_initializer(mean=0, stddev=1))

# reshape the matrices to grapy and colored
w_gray_reshaped = tf.reshape(w_gray, (2, 25, 15, 1))
w_color_reshaped = tf.reshape(w_color, (2, 25, 15, 3))

# create the image summaries
gs_summary = tf.summary.image('Grayscale', w_gray_reshaped)
c_summary = tf.summary.image('Color', w_color_reshaped, max_outputs=5)

#merge all summaries
merged = tf.summary.merge_all()

# create the op for initializing all variables
init = tf.global_variables_initializer()

# launch the graph in a session
with tf.Session() as sess:
    
    # creating the writer inside the session
    writer = tf.summary.FileWriter('./graphs', sess.graph)
    
    # initialize all variables
    sess.run(init)
    
    # evaluate the merged op to get the summaries
    summary = sess.run(merged)
    writer.add_summary(summary)

In [102]:
 # To clear the defined variables and operations of the previous cell
tf.compat.v1.reset_default_graph()  

# create the variables for colored and grayscale images
w_gray = tf.compat.v1.get_variable('W_Grayscale', shape=[50, 30], initializer=tf.compat.v1.truncated_normal_initializer(mean=0, stddev=1))
w_color = tf.compat.v1.get_variable('W_Color', shape=[50, 30], initializer=tf.compat.v1.truncated_normal_initializer(mean=0, stddev=1))

# reshape the matrices to grapy and colored
w_gray_reshaped = tf.compat.v1.reshape(w_gray, (2, 50, 15, 1))
w_color_reshaped = tf.compat.v1.reshape(w_color, (2, 25, 10, 3))

# create the image summaries
gs_summary = tf.compat.v1.summary.image('Grayscale', w_gray_reshaped)
c_summary = tf.compat.v1.summary.image('Color', w_color_reshaped, max_outputs=2)

#merge all summaries
merged = tf.compat.v1.summary.merge_all()

# create the op for initializing all variables
init = tf.compat.v1.global_variables_initializer()

# launch the graph in a session
with tf.compat.v1.Session() as sess:
    
    # creating the writer inside the session
    writer = tf.compat.v1.summary.FileWriter('./graphs', sess.graph)
    
    # initialize all variables
    sess.run(init)
    
    # evaluate the merged op to get the summaries
    summary = sess.run(merged)
    writer.add_summary(summary)

In [103]:
# importing tensorflow dataset
from tensorflow.keras.datasets import fashion_mnist

# loading the testing and training dataset
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

4422102/4422102 [==============================] - 8s 2us/step


In [118]:
y_train

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [104]:
# Normalizing the dataset
X_train = X_train/255.0
X_test = X_test/255.0

In [105]:
# Reshaping the dataset
X_train = X_train.reshape(-1, 28*28)
X_test = X_test.reshape(-1, 28*28)

In [106]:
# Creating a model object
model = tf.keras.models.Sequential()

In [107]:
# Frist fully connected layer
model.add(tf.keras.layers.Dense(units = 128, activation = 'relu', input_shape = (784,)))

In [108]:
# Adding drop out layer
model.add(tf.keras.layers.Dropout(0.2))

In [109]:
# Output Layer
model.add(tf.keras.layers.Dense(units = 10, activation = 'softmax'))

In [110]:
# complining the model
model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['sparse_categorical_accuracy'])


In [111]:
# Training the model
model.fit(X_train, y_train, epochs =5)


Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 6s 106us/sample - loss: 0.5346 - sparse_categorical_accuracy: 0.8088
Epoch 2/5
60000/60000 [==============================] - 3s 52us/sample - loss: 0.3990 - sparse_categorical_accuracy: 0.8547
Epoch 3/5
60000/60000 [==============================] - 3s 51us/sample - loss: 0.3687 - sparse_categorical_accuracy: 0.8659
Epoch 4/5
60000/60000 [==============================] - 3s 52us/sample - loss: 0.3469 - sparse_categorical_accuracy: 0.8729
Epoch 5/5
60000/60000 [==============================] - 3s 50us/sample - loss: 0.3300 - sparse_categorical_accuracy: 0.8788


In [119]:
# Evaluating the model
test_accuracy = model.evaluate(X_test, y_test)


In [113]:
# acuracy score
print(test_accuracy)

0.8769
